# Generated by Django 3.2.9 on 2021-11-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StationName', models.CharField(max_length=234)),
                ('StationLocation', models.CharField(max_length=234)),
                ('NoOfCars', models.IntegerField()),
            ],
        ),
    ]
