# Generated by Django 3.2.9 on 2021-11-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car_Tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_Number', models.CharField(max_length=20)),
                ('Car_model', models.CharField(max_length=234)),
                ('Car_Mileage', models.IntegerField()),
            ],
        ),
    ]
