# Generated by Django 3.2.9 on 2021-11-10 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car_Tracker', '0002_vehicles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='NoOfCars',
        ),
    ]
