# Generated by Django 3.2.9 on 2021-11-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car_Tracker', '0003_remove_station_noofcars'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='stations',
            field=models.ManyToManyField(to='Car_Tracker.Station'),
        ),
    ]
